# Generated by Django 4.2.5 on 2023-10-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('body_style', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('interior', models.CharField(blank=True, max_length=100, null=True)),
                ('conditon', models.CharField(choices=[('used', 'It is used'), ('unused', 'It is not used')], default='unused', max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
    ]
