# Generated by Django 4.2.5 on 2023-10-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmessage',
            old_name='car',
            new_name='car1',
        ),
    ]
