# Generated by Django 4.2.5 on 2023-10-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_car_carmessage_car1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmessage',
            old_name='car1',
            new_name='car',
        ),
    ]
