# Generated by Django 4.2.5 on 2023-10-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_age'),
        ('cars', '0005_rename_car1_carmessage_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmessage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='carmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='accounts.profile'),
        ),
    ]
